// <auto-generated />
using System;
using HotelBookingApp.API.Hotels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingApp.API.Hotels.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("HotelBookingApp.API.Hotels.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelStreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HotelID");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("HotelBookingApp.API.Hotels.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RoomAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoomID");

                    b.HasIndex("HotelID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HotelBookingApp.API.Hotels.Models.Room", b =>
                {
                    b.HasOne("HotelBookingApp.API.Hotels.Models.Hotel", null)
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelID");
                });

            modelBuilder.Entity("HotelBookingApp.API.Hotels.Models.Hotel", b =>
                {
                    b.Navigation("HotelRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
